CREATE SCHEMA IF NOT EXISTS waiter;

CREATE TABLE IF NOT EXISTS waiter.user (
  "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL
  , "email" VARCHAR(255) NOT NULL
  , "password" VARCHAR(255) NOT NULL
  , "balance" BIGINT NOT NULL
);
