version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: db-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-tipped}
      PGDATA: /data/postgres
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${POSTGRES_DB:-tipped}",
          "-U",
          "${POSTGRES_USER:-postgres}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    command: ["-c", "log_statement=all"]
    ports:
      - 5432:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
